version: '3'

services:
  app:
    image: 'futzmann/pft:latest'
    build:
      context: .
    container_name: 'pft-app'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - /etc/jenkins-env/.env.dev
    ports:
      - "8081:8080"

  db:
    image: 'postgres'
    container_name: 'db'
    env_file:
      - /etc/jenkins-env/.env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  pgdata: