version: '3'

services:
  app:
    image: 'pftdev:latest'
    build:
      context: .
    container_name: 'pft-app'
    depends_on:
      - db
    env_file:
      - ./.env.dev
    ports:
      - "8080:8080"

  db:
    image: 'postgres'
    container_name: 'db'
    env_file:
      - ./.env.db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


