pipeline {
    agent any

    stages {
        stage('Build maven') {
            steps {
                sh "cd pft && mvn clean install -DskipTests"
            }
        }
        stage('Build docker') {
            steps {
                sh "cd pft && docker build -t pftdev ."
            }
        }
    }
}