pipeline {
    agent {
        node {
            label 'spring-build-experimental'
            customWorkspace '/var/lib/jenkins/workspace/spring-experimental/pft'
        }
    }

    stages {
        stage('Build maven') {
            steps {
                sh "mvn clean install"
            }
        }
        stage('Build docker') {
            steps {
                sh "docker build -t pftdev ."
            }
        }
    }
}