pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/Frutzmann/Portfolio-Management-Tracker'
            }
        }
        stage('Build maven') {
            steps {
                mvn clean install
            }
        }
    }
}